on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Add Go
        uses: actions/setup-go@v2
      - name: Build
        run: |
          cd ./ci && go mod download && go run .
      - name: Release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}